HomWork30-31
ToffeeGalka/DP pull request #1
Opened 2024-06-17 13:04 UTC by ToffeeGalka

HomWork30-31

2024-06-20 18:03 UTC, dkobzin requested changes

2024-06-20 18:03 UTC, dkobzin commented on WebApi/Controllers/PatientController.cs
> +            }
Пожалуйста перенесите проверку в сервис

2024-06-20 18:03 UTC, dkobzin commented on WebApi/Controllers/PatientController.cs
> +            if (patients == null)
Пожалуйста перенесите в сервис

2024-06-20 18:03 UTC, dkobzin commented on WebApi/Services/PatientService.cs
> +            oldEditPatient.Phone = patient.Phone;
Вынесите пожалуйста в маппер

2024-06-20 18:10 UTC, dkobzin commented on WebApi/Services/PatientService.cs
> +            oldEditPatient.Phone = patient.Phone;
Следующие замечания:
1. Архитектура приложения - 3 уровня. WebApi, Buisness,  Data.
2. WebApi - тонкие контроллеры + сервисы из Buisness. Они только передают модели в сервисы и принимают из них сервисы.
3. Buisness - сервисы + валидация через интерфейсы + мапперы  с модели на сущности БД
4. Data - репозитории + сущности + файлы конфигурации сущностей +  DbContext + фабрика если это нужно.
Надеюсь что к след. вторнику сможете подправить данный ПР и мы сможем по нему пройтись еще раз. Коммиты делайте в эту же ветку чаще после каждого изменения.

2024-06-21 07:06 UTC, ToffeeGalka commented on WebApi/Controllers/PatientController.cs
> +            }
Вы же сами в дз писали, что валидацию нужно сделать на контроллере

2024-06-22 07:21 UTC, dkobzin commented on WebApi/Controllers/PatientController.cs
> +            }
Валидацию на модель которая приходит - т.е. к примеру на параметр Id или что модель не пустая. На сервисе делается валидация бизнес логики - т.е. что в модели допустимые значения для какого либо поля, его длина, зависимости от одного поля на другое.

2024-06-25 05:54 UTC, dkobzin approved these changes

2024-06-25 05:54 UTC, dkobzin commented on Business/Services/IPatientService.cs
> +        public Task DeletePatient(int idPatient);
Добавьте пожалуйста Get и GetAll

2024-06-25 05:54 UTC, dkobzin commented on Business/Services/PatientService.cs
> +            }
Тут лучше ввести Enum и сравнивать не по "магическим" символьным константам

2024-06-25 05:54 UTC, dkobzin commented on Business/Services/PatientService.cs
> +            //oldEditPatient.Phone = patient.Phone;
Уберите пожалуйста закомментированный код

2024-06-25 05:54 UTC, dkobzin commented on WebApi/Controllers/PatientController.cs
> +            if (patients == null)
Можно тут добавить проверку на то что параметр равен 0 или вообще отстсутсвует

2024-06-25 05:54 UTC, dkobzin commented on Business/Services/PatientService.cs
> +            }
И перенести логику в отдельный класс валидаторов, наследуемый поведение от интерфейса.

2024-06-25 05:55 UTC, merged