AllClass
ToffeeGalka/DP pull request #3
Opened 2024-07-15 13:11 UTC by ToffeeGalka

2024-07-16 05:35 UTC, dkobzin requested changes

2024-07-16 05:35 UTC, dkobzin commented on Business/Services/DispRegService.cs
> +        public async Task<int> AddDispReg(DispReg dispReg)
Отсутствует проверка входной параметров на nul с выдачей исключения. То же сделайте для всех конструкторов и методов

2024-07-16 05:35 UTC, dkobzin commented on Business/Services/DispRegService.cs
> +            var oldEditDispReg = await dbContext.DispRegs.FirstOrDefaultAsync(p => p.Id == dispReg.Id);
Пишите пожалуйста более полные и информативные имена переменных в сите  camelCase

2024-07-16 05:35 UTC, dkobzin commented on Business/Services/DispRegService.cs
> +            DispRegValidator.Validate(dispReg);
Нет проверки если модель не валидно. Дальнейшие действия?

2024-07-16 05:35 UTC, dkobzin commented on Business/Services/DispRegService.cs
> +            DispRegValidator.Validate(dispReg);
То же касается всех остальных методов и классов

2024-07-16 05:35 UTC, dkobzin commented on Business/Services/DispRegService.cs
> +            DispRegValidator.Validate(dispReg);
Не использайте стат. классы - используйте классы полученные через  DI / IoC    интерфейсы. Это касается всех остальных классов валидаторов и мапперов

2024-07-18 14:05 UTC, ToffeeGalka commented on Business/Services/DispRegService.cs
> +        public async Task<int> AddDispReg(DispReg dispReg)
fix

2024-07-18 14:05 UTC, ToffeeGalka commented on Business/Services/DispRegService.cs
> +            DispRegValidator.Validate(dispReg);
fix

2024-07-18 14:05 UTC, ToffeeGalka commented on Business/Services/DispRegService.cs
> +            DispRegValidator.Validate(dispReg);
fix

2024-07-18 14:05 UTC, ToffeeGalka commented on Business/Services/DispRegService.cs
> +            var oldEditDispReg = await dbContext.DispRegs.FirstOrDefaultAsync(p => p.Id == dispReg.Id);
как по мне, так тут все понятно ), не поправляла

2024-07-22 04:46 UTC, dkobzin approved these changes

2024-07-22 08:45 UTC, merged